// <auto-generated />
namespace test.Migrations.ContextShipControl
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddShipControl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShipControl));
        
        string IMigrationMetadata.Id
        {
            get { return "201703140902335_AddShipControl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
