// <auto-generated />
namespace test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SuperOptyMonday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuperOptyMonday));
        
        string IMigrationMetadata.Id
        {
            get { return "201702130838347_SuperOpty-Monday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
